"""empty message

Revision ID: 21db6ac88163
Revises: 07550924ee32
Create Date: 2020-05-17 10:10:02.286624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21db6ac88163'
down_revision = '07550924ee32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'exchange', 'hospital', ['hospital2'], ['id'])
    op.add_column('ppe', sa.Column('manu', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ppe', 'manu')
    op.drop_constraint(None, 'exchange', type_='foreignkey')
    # ### end Alembic commands ###
