"""empty message

Revision ID: 61808f55e98d
Revises: 21db6ac88163
Create Date: 2020-09-29 01:30:10.209265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61808f55e98d'
down_revision = '21db6ac88163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'exchange', 'hospital', ['hospital2'], ['id'], ondelete='CASCADE')
    op.drop_column('hospital', 'address')
    op.add_column('ppe', sa.Column('box_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ppe', 'box_size')
    op.add_column('hospital', sa.Column('address', sa.VARCHAR(length=140), nullable=True))
    op.drop_constraint(None, 'exchange', type_='foreignkey')
    # ### end Alembic commands ###
