"""empty message

Revision ID: b0ac5e59619e
Revises: 754216a07736
Create Date: 2020-04-13 13:22:06.603217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ac5e59619e'
down_revision = '754216a07736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchanges', sa.Column('created_timestamp', sa.DateTime(), nullable=True))
    op.add_column('exchanges', sa.Column('updated_timestamp', sa.DateTime(), nullable=True))
    op.drop_column('exchanges', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchanges', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.drop_column('exchanges', 'updated_timestamp')
    op.drop_column('exchanges', 'created_timestamp')
    # ### end Alembic commands ###
